spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

---

springdoc:
  swagger-ui:
    path: /e-commerce.html
  api-docs:
    path: /api-docs
  packages-to-scan: kr.hhplus.be.server
  group-configs:
    - group: hhplus
      paths-to-match: /api/**


spring.config.activate.on-profile: local, test

spring:
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 30000
    url: jdbc:mysql://localhost:3305/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  redisson:
    config: |
      singleServerConfig:
        address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
      threads: 4
      nettyThreads: 8
      lockWatchdogTimeout: 30000
      codec: !<org.redisson.codec.JsonJacksonCodec> {}    
logging:
  level:
    org.springframework.cache: TRACE


  # === Redisson 설정 추가 ===
#  redisson:
#    # Testcontainers가 주입한 host/port로 연결
#    address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
#    threads: 4
#    nettyThreads: 8
#    lockWatchdogTimeout: 30000   # 자동 락 해제 시간(ms)
#    codec: org.redisson.codec.JsonJacksonCodec
#
#
