spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

---

springdoc:
  swagger-ui:
    path: /e-commerce.html
  api-docs:
    path: /api-docs
  packages-to-scan: kr.hhplus.be.server
  group-configs:
    - group: hhplus
      paths-to-match: /api/**


spring.config.activate.on-profile: local, test

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234